services:
    app:
      container_name: app
      build:
        dockerfile: Dockerfile
      command:
        - "python"
        - "app/main.py"
      restart: always
      ports:
        - "8000:8000"
      depends_on:
        db:
          condition: service_healthy

    db:
      image: postgres:16.2
      container_name: db
      restart: always
      env_file:
        - .template.env.docker
      volumes:
        - db:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
        interval: 2s
        timeout: 5s
        retries: 5

volumes:
  db:
    driver: local
